Assignment 3: Predicting Loan Repayment
========================================================
Loading and Pre-Processing the Dataset
-------------------------------------------------------
```{r}
loans = read.csv("loans.csv")
str(loans)
summary(loans)
```
Imputation of Missing Values
-----------------------------------------------------
```{r}
#library(mice)
#set.seed(144)
#vars.for.imputation = setdiff(names(loans), "not.fully.paid")
#imputed = complete(mice(loans[vars.for.imputation]))
#loans[vars.for.imputation] = imputed
loans = read.csv("loans_imputed.csv")
```
Splitting the data
------------------------------------------------------
```{r}
set.seed(144)
library(caTools)
split = sample.split(loans$not.fully.paid, SplitRatio = 0.7)
train = subset(loans, split == TRUE)
test = subset(loans, split == FALSE)
c(nrow(train), nrow(test))
```

Building our Logistic Regression Model
-----------------------------------------------------
```{r}
Model1 = glm(not.fully.paid ~ ., data=train,  family=binomial)
summary(Model1)
```
Predicting With Specific Observations
---------------------------------------------
Person with 700 Fico score (A) vs. 710 FICO Score (B)
```{r}
Model1$coefficients
ficoBeta = Model1$coefficients[13]
700 * ficoBeta - 710 * ficoBeta
exp(700 * ficoBeta) / exp(710 * ficoBeta)
```
Predictions on the Test Set
-----------------------------------------------------
```{r}
predicted.risk = predict(Model1, type="response", newdata=test)
test$predicted.risk = predicted.risk
summary(predicted.risk)
PredTable = table(test$not.fully.paid, predicted.risk >= 0.5)
PredTable
```
Sensitivity:
```{r}
(PredTable[2,2]/sum(PredTable[2,]))
```
Specificity:
```{r}
(PredTable[1,1]/sum(PredTable[1,]))
```
Accuracy:
```{r}
(PredTable[1,1] + PredTable[2,2]) / nrow(test)
```
Baseline Model (Everyone is a non-violator)
```{r}
table(test$not.fully.paid)
mean(test$not.fully.paid == 0)
```
ROCR Production
------------------------------------------------------
```{r}
library(ROCR)
ROCRpred = prediction(predicted.risk, test$not.fully.paid)
as.numeric(performance(ROCRpred, "auc")@y.values)
```
Model 2: Bivariate Logistic Regression Model Using int.rate
========================================================
```{r}
Model2 = glm(not.fully.paid ~ int.rate, data=train, family=binomial)
summary(Model2)
```
Predictions on the Test Set for Model 2
-----------------------------------------------------
```{r}
Pred2 = predict(Model2, type="response", newdata=test)
summary(Pred2)
PredTable = table(test$not.fully.paid, Pred2 >= 0.5)
PredTable
```
Baseline Model (Everyone is a non-violator)
```{r}
table(test$not.fully.paid)
mean(test$not.fully.paid == 0)
```
ROCR Production for Model 2
------------------------------------------------------
```{r}
library(ROCR)
ROCRpred = prediction(Pred2, test$not.fully.paid)
as.numeric(performance(ROCRpred, "auc")@y.values)
```
Testing a Simple Investment Strategy
========================================================
Looking at the test set, if test$not.fully.paid == 1, then we assume a total loss of the principle, so the profit must be set to -1 (we assume all principles == 1 for each observation in the test dataset.)
```{r}
test$profit = exp(test$int.rate*3) - 1
test$profit[test$not.fully.paid == 1] = -1
```
The maximum prof it of a $10 investment in any loan in the testing set is:
```{r}
10 * max(test$profit)
```
An Investment Strategy Based on Prediction
========================================================
```{r}
highInterest = subset(test, int.rate >= 0.15)
```
Average Profit of this dataset
```{r}
mean(highInterest$profit)
table(highInterest$not.fully.paid)
```
Determining the 100 Loans most likely to pay
---------------------------------------------------------
```{r}
cutoff = sort(highInterest$predicted.risk, decreasing=FALSE)[100]
selectedLoans = subset(highInterest, predicted.risk <= cutoff)
sum(selectedLoans$profit)
summary(selectedLoans$profit)
table(selectedLoans$not.fully.paid)
```

